[workspace]
[package]
version = "0.1.0"
name = "blobsp1-script"
edition = "2021"

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
celestia-rpc = { git = "https://github.com/S1nus/lumina.git", branch = "connor/index-field" }
celestia-types = { git = "https://github.com/S1nus/lumina.git", branch = "connor/index-field" }
serde_json = "1.0.114"
bincode = "1.3.3"
nmt-rs = { git = "https://github.com/S1nus/nmt-rs.git" }
